# ==========================================================
# GLOBAL DEFAULTS
# ==========================================================
defaults:

  # Where compiled SQL templates live
  sql_templates_dir: sql_templates

  # Where Excel outputs are written
  output_dir: C:/Users/nathan.taylor/Asurion/Coaching & Technology - BPC Data/Proposed_Cohorts

   # Log directory
  log_dir: logs

   # Optional global behavior flags
  apply_site_exclusions_by_default: true

# ==========================================================
# JOB DEFINITIONS
# ==========================================================
jobs:

  # ======================================================
  #  20 VZW SOL – CRT Hangup
  # ======================================================
- name: VZW_SOL_CRT_Hangup

  query:
    query_type: smart_offer
    sql_template: transfer_hangup.sql

  inputs:
    client: Verizon
    business_unit: Soluto
    cohort_id: '5'
    date_start: '2026-02-27'
    date_end: '2026-03-13'

  coaching_override: CRT Hangup
  reference_link: https://app.powerbi.com/groups/me/reports/30d76537-2dea-4dc8-a2ea-b1d085303f15?ctid=64e5ad32-cb04-44df-8896-bed5d7792429&pbi_source=linkShare

  validity:
    denominator_limit: 5

  eligibility:
    site_exclude_contains: []

    filters: []

  selection:
    outlier_limit_target: percentile
    outlier_limit: 0.75
    metric_direction: lower_is_good
    outlier_side: worst

  comparisons: []

  enrichments:
    - name: recording_link
      query:
        query_type: recording
        sql_template: outdial_recording_links.sql
      inputs_override:
        client: "Verizon"
        business_unit: "Soluto"
        date_start: "2026-02-27"
        date_end: "2026-03-11"
        min_outdial_seconds: 90
      join:
        on: ["expert_id"]
        how: left
      map_columns:
        recording_link: recording_link